name: "Youappz Deploy"
description: "A composite action that prepares your Jamstack site to be deployed to Youappz platform"
branding:
  icon: "box"
  color: "orange"
inputs:
  path:
    description: "Path of the directory containing your site"
    required: false
    default: "."
  node-version:
    description: "The node version to use"
    required: false
    default: "16"
  package-manager:
    description: "If not automatically detectable, you may specify your preferred package manager"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: check is APPZ_API_KEY exists
      id: apikey
      shell: "bash"
      run: |
        if [[ "$APPZ_API_KEY" == '' ]]; then
          echo "secret APPZ_API_KEY has not been set"
          echo please go to \"settings \> secrets \> actions\" to create it
          exit 1          
        fi

    - name: Check lockfiles
      id: lockfile
      shell: "bash"
      env:
        INPUT_PM: ${{ inputs.package-manager }}
      run: |
        len=`echo $INPUT_PM | wc -c`
        if [ $len -gt 1 ]; then
            echo "::set-output name=PACKAGE_MANAGER::$INPUT_PM"
            echo "node_pm=$INPUT_PM" >> $GITHUB_ENV
        elif [ $(find "." -name "pnpm-lock.yaml") ]; then
            echo "::set-output name=PACKAGE_MANAGER::pnpm"
            echo "node_pm=pnpm" >> $GITHUB_ENV
        elif [ $(find "." -name "yarn.lock") ]; then 
            echo "::set-output name=PACKAGE_MANAGER::yarn"
            echo "node_pm=yarn" >> $GITHUB_ENV
        elif [ $(find "." -name "package-lock.json") ]; then 
            echo "::set-output name=PACKAGE_MANAGER::npm"
            echo "node_pm=npm" >> $GITHUB_ENV
        else
            echo "No lockfile found.
        Please specify your preferred \"package-manager\" in the action configuration."
            exit 1
        fi

    - name: Setup PNPM
      if: ${{ steps.lockfile.outputs.PACKAGE_MANAGER == 'pnpm' }}
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 7.x.x

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ steps.lockfile.outputs.PACKAGE_MANAGER }}

    - name: Install Youappz Cli
      shell: "bash"
      run: npm install --global @youappz/cli@latest

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: "${{ inputs.path }}/node_modules"
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install
      shell: "bash"
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd ${{ inputs.path }}
        $node_pm install

    - name: Build
      shell: "bash"
      env:
        PACKAGE_MANAGER: ${{ steps.lockfile.outputs.PACKAGE_MANAGER }}
      run: |
        cd ${{ inputs.path }}
        $node_pm run build --if-present

    - name: Deploy Project Artifacts to Youappz
      shell: "bash"
      run: |
        cd ${{ inputs.path }}
        appz deploy -d dist
